version: "3.7"

services:
  backend:
    image: node:20.10.0-bookworm-slim
    environment:
      - TZ=Europe/Amsterdam
      - NODE_ENV=production
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    command: "npm start"
    links:
      - rethinkdb:db
    ports:
      - "3000:3000"
  rethinkdb:
    image: rethinkdb:2.4.4-bookworm-slim
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "8080:8080"
    volumes:
      - /data
